# a new command has to be added to composer.json for it to be included in README.md.
# (note: updating composer.json has been automated via update-composer-json-commands.yml.)

name: regenerate README.md
on:
  workflow_run:
    workflows:
      - "update commands section in composer.json"
    types:
      - completed
  # run this workflow manually
  workflow_dispatch:

env:
  README: README.md
  WP_CLI_PACKAGES_DIR: /root/.wp-cli/packages

permissions:
  contents: write

jobs:
  regenerate-readme:
    name: Regenerate README.md and commit it back to the repository
    runs-on: ubuntu-latest
    timeout-minutes: 3
    container:
      image: ghcr.io/baizman-design/wp-cli-package
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.BD_ACCESS_TOKEN }}
    steps:
      - name: check out the repository
        uses: actions/checkout@v4
      - name: generate the command's documentation
        run: |
          composer dump-autoload
          wp scaffold package-readme --branch=${{ github.event.repository.default_branch }} --force .
      - name: commit documentation, if needed
        run: |
          git config --global --add safe.directory '*'
          git config --global user.name 'Saul Baizman'
          git config --global user.email 'baizman-design@users.noreply.github.com'
          set +e
          git diff --quiet --exit-code
          if [ $? -eq 1 ]
          then
          set -e
          added="$(git diff --numstat ${README} | awk '{print $1}')"
          echo "lines added: ${added:-0}" | tee -a ${GITHUB_STEP_SUMMARY}
          deleted="$(git diff --numstat ${README} | awk '{print $2}')"
          echo "lines deleted: ${deleted:-0}" | tee -a ${GITHUB_STEP_SUMMARY}
          git add ${README}
          git commit -m "Updated ${README} via GHA."
          git push
          echo "changes were successfully committed to the repository." | tee -a ${GITHUB_STEP_SUMMARY}
          else
          echo "it appears nothing changed." | tee -a ${GITHUB_STEP_SUMMARY}
          fi
